import { NextResponse } from "next/server"

type Recipe = {
  id: string
  name: string
  category: string
  icon: "coffee" | "utensils" | "apple" | "leaf" | "zap"
  image: string
  prepTime: number
  servings: number
  difficulty: "Kolay" | "Orta" | "Zor"
  rating: number
  calories: number
  protein: number
  carbs: number
  fat: number
  tags: string[]
  ingredients: Array<{ name: string; amount: string }>
  instructions: string[]
  tips?: string
}

const recipes: Recipe[] = [
  {
    id: "protein-pancake",
    name: "Protein Pankek",
    category: "Kahvaltı",
    icon: "coffee",
    image: "/protein-pancakes-with-berries.png",
    prepTime: 15,
    servings: 2,
    difficulty: "Kolay",
    rating: 4.8,
    calories: 320,
    protein: 28,
    carbs: 25,
    fat: 12,
    tags: ["Yüksek Protein", "Düşük Kalori", "Glutensiz"],
    ingredients: [
      { name: "Yulaf unu", amount: "50 g" },
      { name: "Vanilyalı protein tozu", amount: "30 g" },
      { name: "Yumurta", amount: "2 adet" },
      { name: "Laktozsuz süt", amount: "100 ml" },
      { name: "Muz", amount: "1 adet" },
      { name: "Tarçın", amount: "1 çay kaşığı" },
      { name: "Kabartma tozu", amount: "1 çay kaşığı" },
    ],
    instructions: [
      "Kuru malzemeleri derin bir kapta karıştırın.",
      "Muzu ezin, yumurta ve süt ile birlikte ayrı bir kapta çırpın.",
      "Yaş ve kuru karışımları birleştirip pürüzsüz kıvama getirin.",
      "Tavayı hafifçe yağlayıp orta ateşte pankekleri pişirin.",
      "Her iki yüzü kızarınca tabağa alıp meyve ile servis edin.",
    ],
    tips: "Daha kabarık pankek için yumurta akını ayrı çırpıp son anda karışıma ekleyin.",
  },
  {
    id: "chicken-salad",
    name: "Izgara Tavuk Salatası",
    category: "Ana Yemek",
    icon: "utensils",
    image: "/grilled-chicken-salad.png",
    prepTime: 25,
    servings: 1,
    difficulty: "Orta",
    rating: 4.6,
    calories: 380,
    protein: 42,
    carbs: 18,
    fat: 16,
    tags: ["Yüksek Protein", "Düşük Karbonhidrat", "Glutensiz"],
    ingredients: [
      { name: "Tavuk göğsü", amount: "150 g" },
      { name: "Karışık yeşillik", amount: "100 g" },
      { name: "Cherry domates", amount: "8 adet" },
      { name: "Salatalık", amount: "1 adet" },
      { name: "Avokado", amount: "1/2 adet" },
      { name: "Zeytinyağı", amount: "1 yemek kaşığı" },
      { name: "Limon suyu", amount: "1 yemek kaşığı" },
      { name: "Tuz ve karabiber", amount: "Damla" },
    ],
    instructions: [
      "Tavuk göğsünü tuz, karabiber ve zeytinyağı ile marine edin.",
      "Izgarada veya döküm tavada her iki yüzünü pişirip dilimleyin.",
      "Yeşillikleri yıkayıp kurulayın, sebzeleri doğrayın.",
      "Tabana yeşillikleri serip diğer malzemeleri ekleyin.",
      "Zeytinyağı ve limon suyundan basit sos hazırlayıp üzerine dökün.",
    ],
    tips: "Marine aşamasında tavuğu en az 30 dakika bekletmek lezzeti artırır.",
  },
  {
    id: "protein-smoothie",
    name: "Antrenman Sonrası Smoothie",
    category: "Atıştırmalık",
    icon: "apple",
    image: "/protein-smoothie-with-fruits.png",
    prepTime: 5,
    servings: 1,
    difficulty: "Kolay",
    rating: 4.9,
    calories: 280,
    protein: 32,
    carbs: 28,
    fat: 8,
    tags: ["Yüksek Protein", "Antrenman Sonrası", "Vegan Seçenek"],
    ingredients: [
      { name: "Vanilyalı protein tozu", amount: "30 g" },
      { name: "Badem sütü", amount: "200 ml" },
      { name: "Muz", amount: "1 adet" },
      { name: "Yaban mersini", amount: "50 g" },
      { name: "Badem ezmesi", amount: "1 yemek kaşığı" },
      { name: "Chia tohumu", amount: "1 tatlı kaşığı" },
      { name: "Buz", amount: "5 küp" },
    ],
    instructions: [
      "Tüm malzemeleri blender’a ekleyin.",
      "Yüksek devirde 1-2 dakika karıştırın.",
      "Kıvamı kontrol edip gerekirse biraz daha süt ilave edin.",
      "Soğuk olarak hemen servis edin.",
    ],
    tips: "Smoothie’yi önceden hazırlayıp dondurarak buzlu kaseler yapabilirsiniz.",
  },
  {
    id: "overnight-oats",
    name: "Gece Beklemiş Yulaf",
    category: "Kahvaltı",
    icon: "coffee",
    image: "/overnight-oats-with-berries-and-nuts.png",
    prepTime: 5,
    servings: 1,
    difficulty: "Kolay",
    rating: 4.7,
    calories: 350,
    protein: 18,
    carbs: 45,
    fat: 12,
    tags: ["Hazır Kahvaltı", "Yüksek Lif", "Vegan"],
    ingredients: [
      { name: "Yulaf ezmesi", amount: "50 g" },
      { name: "Chia tohumu", amount: "1 yemek kaşığı" },
      { name: "Badem sütü", amount: "150 ml" },
      { name: "Yoğurt", amount: "2 yemek kaşığı" },
      { name: "Bal", amount: "1 tatlı kaşığı" },
      { name: "Vanilya özütü", amount: "1 çay kaşığı" },
      { name: "Taze meyve", amount: "Damla" },
      { name: "Ceviz", amount: "Damla" },
    ],
    instructions: [
      "Yulaf, chia ve vanilyayı kavanoza alın.",
      "Süt ve yoğurdu ekleyip karıştırın, ardından bal ile tatlandırın.",
      "Kavanozu kapatıp buzdolabında en az 4 saat bekletin.",
      "Servisten önce meyve ve ceviz ile süsleyin.",
    ],
    tips: "Haftalık meal prep için birden fazla kavanoz hazırlanabilir.",
  },
  {
    id: "tuna-wrap",
    name: "Ton Balıklı Fit Wrap",
    category: "Ana Yemek",
    icon: "utensils",
    image: "/tuna-wrap-with-vegetables.png",
    prepTime: 10,
    servings: 1,
    difficulty: "Kolay",
    rating: 4.4,
    calories: 420,
    protein: 35,
    carbs: 32,
    fat: 18,
    tags: ["Pratik", "Yüksek Protein", "Öğle Yemeği"],
    ingredients: [
      { name: "Ton balığı (suda)", amount: "1 konserve" },
      { name: "Tam buğday tortilla", amount: "1 adet" },
      { name: "Yoğurt", amount: "2 yemek kaşığı" },
      { name: "Limon suyu", amount: "1 tatlı kaşığı" },
      { name: "Marul yaprağı", amount: "4 adet" },
      { name: "Domates", amount: "1 adet" },
      { name: "Salatalık", amount: "1/2 adet" },
      { name: "Avokado", amount: "1/2 adet" },
    ],
    instructions: [
      "Ton balığının suyunu süzüp yoğurt ve limon suyu ile karıştırın.",
      "Marul, domates ve salatalığı ince dilimleyin.",
      "Tortillayı serip önce marulu yerleştirin.",
      "Üzerine ton balığı karışımı ve dilimlenmiş sebzeleri ekleyin.",
      "Sıkıca sarıp ortadan ikiye keserek servis edin.",
    ],
    tips: "Wrap’i tost makinesinde ısıtarak çıtırlık katabilirsiniz.",
  },
  {
    id: "sweet-potato-bowl",
    name: "Fırınlanmış Tatlı Patates Bowl",
    category: "Ana Yemek",
    icon: "leaf",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80",
    prepTime: 35,
    servings: 2,
    difficulty: "Kolay",
    rating: 4.5,
    calories: 410,
    protein: 14,
    carbs: 52,
    fat: 14,
    tags: ["Vejetaryen", "Yüksek Lif", "Renkli Tabak"],
    ingredients: [
      { name: "Tatlı patates", amount: "2 adet" },
      { name: "Haşlanmış nohut", amount: "1 su bardağı" },
      { name: "Ispanak", amount: "2 avuç" },
      { name: "Zeytinyağı", amount: "2 yemek kaşığı" },
      { name: "Yoğurt sos", amount: "4 yemek kaşığı" },
      { name: "Nar taneleri", amount: "Damla" },
      { name: "Pul biber", amount: "Damla" },
    ],
    instructions: [
      "Fırını 200°C’ye ısıtın, tatlı patatesleri halka şeklinde doğrayın.",
      "Patatesleri zeytinyağı ve baharatla harmanlayıp 25 dakika fırınlayın.",
      "Nohutu da aynı tepside kızartarak çıtır hale getirin.",
      "Servis kasesine ıspanakları yerleştirip üzerine patates ve nohutu ekleyin.",
      "Yoğurt sosu gezdirip nar taneleriyle süsleyin.",
    ],
    tips: "Ekstra protein için üzerine haşlanmış yumurta dilimleyebilirsiniz.",
  },
  {
    id: "chia-pudding",
    name: "Chia Puding",
    category: "Atıştırmalık",
    icon: "apple",
    image: "https://images.unsplash.com/photo-1464306076886-da185f07f27f?auto=format&fit=crop&w=1200&q=80",
    prepTime: 10,
    servings: 2,
    difficulty: "Kolay",
    rating: 4.6,
    calories: 250,
    protein: 9,
    carbs: 24,
    fat: 12,
    tags: ["Vegan", "Önceden Hazırlık", "Tatlı"],
    ingredients: [
      { name: "Chia tohumu", amount: "6 yemek kaşığı" },
      { name: "Hindistan cevizi sütü", amount: "400 ml" },
      { name: "Akçaağaç şurubu", amount: "1 yemek kaşığı" },
      { name: "Vanilya özütü", amount: "1 çay kaşığı" },
      { name: "Meyve püresi", amount: "Damla" },
    ],
    instructions: [
      "Chia tohumu ve sütü derin bir kapta karıştırın.",
      "Tatlandırıcı ve vanilyayı ekleyip tekrar karıştırın.",
      "Kıvam alması için en az 4 saat buzdolabında bekletin.",
      "Servisten önce meyve püresi ve taze meyvelerle süsleyin.",
    ],
    tips: "Puding çok katı olursa biraz süt ekleyerek kıvamı ayarlayın.",
  },
  {
    id: "quinoa-salad",
    name: "Quinoa Akdeniz Salatası",
    category: "Ana Yemek",
    icon: "leaf",
    image: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1200&q=80",
    prepTime: 20,
    servings: 2,
    difficulty: "Kolay",
    rating: 4.5,
    calories: 360,
    protein: 14,
    carbs: 46,
    fat: 12,
    tags: ["Vejetaryen", "Glutensiz", "Öğle Yemeği"],
    ingredients: [
      { name: "Beyaz quinoa", amount: "1 su bardağı" },
      { name: "Salatalık", amount: "1 adet" },
      { name: "Cherry domates", amount: "10 adet" },
      { name: "Dolmalık biber", amount: "1 adet" },
      { name: "Çekirdeksiz zeytin", amount: "10 adet" },
      { name: "Light beyaz peynir", amount: "50 g" },
      { name: "Zeytinyağı", amount: "2 yemek kaşığı" },
      { name: "Limon suyu", amount: "2 yemek kaşığı" },
      { name: "Taze nane ve maydanoz", amount: "Damla" },
    ],
    instructions: [
      "Quinoayı paket talimatına göre haşlayıp soğutun.",
      "Sebzeleri küçük küpler halinde doğrayın.",
      "Geniş bir kapta tüm malzemeleri birleştirin.",
      "Zeytinyağı ve limon suyu ile sos hazırlayıp salatanın üzerine dökün.",
      "Servis etmeden önce 10 dakika dinlendirin.",
    ],
    tips: "Haşlanmış nohut ekleyerek salatayı daha doyurucu hale getirebilirsiniz.",
  },
  {
    id: "fit-brownie",
    name: "Fit Bakliyat Brownie",
    category: "Tatlı",
    icon: "zap",
    image: "https://images.unsplash.com/photo-1601972599720-761981a0e7c4?auto=format&fit=crop&w=1200&q=80",
    prepTime: 30,
    servings: 8,
    difficulty: "Orta",
    rating: 4.3,
    calories: 190,
    protein: 8,
    carbs: 22,
    fat: 8,
    tags: ["Tatlı Krizi", "Şekersiz", "Yüksek Lif"],
    ingredients: [
      { name: "Haşlanmış siyah fasulye", amount: "1 konserve" },
      { name: "Yumurta", amount: "2 adet" },
      { name: "Toz kakao", amount: "3 yemek kaşığı" },
      { name: "Yer fıstığı ezmesi", amount: "2 yemek kaşığı" },
      { name: "Bal veya hurma şurubu", amount: "3 yemek kaşığı" },
      { name: "Kabartma tozu", amount: "1 çay kaşığı" },
      { name: "Bitter çikolata parçaları", amount: "2 yemek kaşığı" },
    ],
    instructions: [
      "Fasulyeyi sudan geçirip süzün, mutfak robotunda püre haline getirin.",
      "Yumurta, kakao, fıstık ezmesi ve balı ekleyip karıştırın.",
      "Kabartma tozunu spatula ile karışıma yedirin.",
      "Yağlı kağıt serili kalıba döküp üzerine çikolata parçaları serpin.",
      "Önceden ısıtılmış 180°C fırında 20 dakika pişirin.",
      "Soğuduktan sonra dilimleyerek servis edin.",
    ],
    tips: "Brownie’yi porsiyonlayıp dondurarak tatlı krizleri için hazır tutabilirsiniz.",
  },
  {
    id: "egg-muffin",
    name: "Mini Yumurta Muffin",
    category: "Kahvaltı",
    icon: "coffee",
    image: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=1200&q=80",
    prepTime: 25,
    servings: 4,
    difficulty: "Kolay",
    rating: 4.5,
    calories: 140,
    protein: 12,
    carbs: 4,
    fat: 8,
    tags: ["Önceden Hazırlık", "Yüksek Protein", "Mini Öğün"],
    ingredients: [
      { name: "Yumurta", amount: "6 adet" },
      { name: "Light kaşar peyniri", amount: "40 g" },
      { name: "Rendelenmiş kabak", amount: "1/2 adet" },
      { name: "Kapya biber", amount: "1/2 adet" },
      { name: "Laktozsuz süt", amount: "3 yemek kaşığı" },
      { name: "Tuz ve karabiber", amount: "Damla" },
      { name: "Maydanoz", amount: "Damla" },
    ],
    instructions: [
      "Fırını 180°C’ye ısıtın, muffin kalıplarını hafifçe yağlayın.",
      "Yumurtaları çırpın, süt, tuz ve karabiber ekleyin.",
      "Rendelenmiş sebzeler ve peyniri karışıma katın.",
      "Karışımı kalıplara paylaştırıp 15 dakika pişirin.",
      "Fırından aldıktan sonra 5 dakika dinlendirip kalıptan çıkarın.",
    ],
    tips: "Soğuyan muffinleri buzdolabında saklayıp mikrodalgada ısıtarak tüketebilirsiniz.",
  },
]

export async function GET() {
  return NextResponse.json({ recipes })
}
